apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: kserve
spec:
  commonName: "kserve-webhook-server-service.$(NAMESPACE).svc"
  dnsNames:
    - "kserve-webhook-server-service.$(NAMESPACE).svc"
