varReference:
  - path: spec/template/spec/containers/image
    kind: Deployment
  - path: data
    kind: ConfigMap
  - kind: Certificate
    path: spec/commonName
  - kind: Certificate
    path: spec/dnsNames
